#!/bin/bash

top_dir="../data/phys"

eos_dir="/eos/totem/data/ctpps/reconstruction/2016/postTS2_alignment_data/version1"

for f in `eos ls "$eos_dir"|grep ".root"`
do
	tag=${f%.*}

	fill=${tag%%_*}
	fill=${fill#fill}

	stream=${tag##*_}

	echo "* $fill, $stream"

	# make work directory
	dir="$top_dir/fill_$fill/$stream/"
	mkdir -p "$dir"

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		echo "    \"root://eostotem.cern.ch/${eos_dir}/${f}\""
		echo ")"
	) > "$dir/input_files.py"

	# if not present, make (default) config
	if [ ! -f "$dir/config.py" ]
	then
		cp "config_template.py" "$dir/config.py"
	fi
done
